#!/usr/bin/env sh

#files=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.py$")
files=$(git diff --cached --name-only --diff-filter=ACM | grep -E "\.py$")

for file in $files; do
    if [[ $file == *.py ]]; then
        black "$file" 
    fi
done

exit 0